export const termsChunk2 = `<h2 id="legal-16"><span>16.</span> Interference</h2>
<p>16.1 Users must not introduce (or cause the introduction of) any virus, spyware or other similar feature that in any way compromises or may compromise the Website and/or the Platform.</p>
<h2 id="legal-17"><span>17.</span> Access</h2>
<p>17.1 Users may only access the Website and Platform through standard means as approved by FPX, and not via methods such as scraping, data mining, the use of a robot or spider, automation or any similar method of extraction or monitoring.</p>
<h2 id="legal-18"><span>18.</span> Security</h2>
<p>18.1 Users agree FPX is entitled to rely on the authenticity and authority of the User username, password and session-specific codes generated by your hardware device to process actions or requests you submit to the Platform or Website and that FPX may do so without further enquiry.</p>
<p>18.2 The internet is inherently insecure, and Users accept the risk that any information stored or transmitted on the internet or through email may be intercepted or subject to unauthorised access or fraudulent behaviour. If Users think someone is accessing their Platform or Website account without your consent or they would like to report disclosure of their account information, please contact FPX at <a href="mailto:sales@sutcliffetrading.com">sales@sutcliffetrading.com</a>.</p>
<h2 id="legal-19"><span>19.</span> Use by other persons and entities</h2>
<p>19.1 Any person or entity that accesses and uses the Website and/or the Platform on behalf of or via another User, including (without limitation) all directors, officers, employees, independent contractors, agents and/or representatives of any User that have been granted access by that User, irrevocably confirms that he, she or it is fully authorised to do so by that User and agrees to these Terms in all respects.</p>
<h2 id="legal-20"><span>20.</span> Intellectual property</h2>
<p>20.1 All Users agree that the FPX owns all of the intellectual property rights existing in the Website and the Platform (and any and all improvements to the same).</p>
<h2 id="legal-21"><span>21.</span> Tax</h2>
<p>21.1 Each User is responsible for payment of all taxes and duties in relation to any transactions they underatke facilitated by the Platform or Website, and each User indemnify FPX for any claims by any tax authority for any underpayment of any tax or levy, and any penalties and/or interest.</p>
<h2 id="legal-22"><span>22.</span> Warranties</h2>
<p>22.1 The Website and Platform is provided on an “as is” and “as available” basis, and accordingly all implied warranties and representations (whether under statute, common law or otherwise) that might apply to or otherwise arise out of these Terms are hereby expressly excluded by FPX to the fullest extent permitted by law.</p>
<p>22.2 Each User hereby warrants and represents that:</p>
<p>1. all information, facts, statements, data and details relating to that User’s products and services that are published, or to be published, on the Website and Platform are true, accurate and correct in all respects and not misleading or deceptive in any respect;</p>
<p>2. it fully owns all intellectual property in the products and services that will be published on the Website and Platform or is otherwise fully and validly licensed by the relevant owner to effect the publication in accordance with these Terms and at law;</p>
<p>3. it has full power and authority to enter into these Terms;</p>
<p>4. all authorisations and approvals that are necessary or required in connection with the User’s entry into these Terms, and the assumption of rights and obligations under these Terms, have been obtained or effected; and</p>
<p>5. the entry into and performance of these Terms by the User does not constitute a breach of any law or obligation and will not cause or result in any default or breach under any other agreement or arrangement by which it is bound and which would prevent the User from entering into or performing its obligations under these Terms.</p>
<p>22.3 Each User agrees that, for the purposes of section 37(2)(a) of the Contract and Commercial Law Act 2017, FPX is entering into these Terms with the User on the basis of, and in reliance on, the warranties and representation given to FPX by the User under these Terms. Accordingly, the truth of the statements contained in those warranties and representations are essential to FPX.</p>
<p>22.4 To the maximum extent permitted by law, we disclaim and exclude all implied conditions and warranties. To avoid doubt, we do not warrant that:</p>
<p>1. the Website or Platform will meet your specific requirements;</p>
<p>2. the Website or Platform will be uninterrupted, timely, secure, or error free;</p>
<p>3. the results that may be obtained from the use of the Platform or Website will be accurate or reliable;</p>
<p>4. the quality of any products, services, information or other material purchased or obtained by you through the Website or Platform will meet your expectations; and</p>
<p>5. any errors in the Website or Platform will be corrected.</p>
<p>22.5 Notwithstanding clause 22.4, we warrant that we are entitled to enter into these Terms and grant the rights for you to use the Website and Platform as set out in these Terms.</p>
<h2 id="legal-23"><span>23.</span> Indemnity</h2>
<p>23.1 Each User hereby indemnifies, and will keep indemnified, FPX against all forms of liability, actions, proceedings, demands, costs, charges and expenses which FPX may incur or be subject to or suffer as a result of that User's use of the Website and Platform, including as a result of any of its warranties or representations about its products and services being false, unsubstantiated, misleading or deceptive.</p>
<p>23.2 Each User hereby indemnifies, and will keep indemnified, FPX against all forms of liability, actions, proceedings, demands, costs, charges and expenses which FPX may incur or be subject to or suffer as a result of:</p>
<p>1. any breach of these Terms by the User; and</p>
<p>2. that User's use of the Website and Platform, including as a result of any of its warranties or representations about its products and services being false, unsubstantiated, misleading or deceptive.</p>
<h2 id="legal-24"><span>24.</span> Feedback</h2>
<p>24.1 We welcome your feedback and ideas on how to improve the Website and Platform.</p>
<p>24.2 If you choose to submit your ideas or suggestions, you agree that we are free to use them without restriction and that you will not have rights to any intellectual property that may be generated as a result.</p>
<h2 id="legal-25"><span>25.</span> Dispute resolution</h2>
<p>25.1 The following provisions shall apply to any dispute arising under or relating to these Terms (a <strong>Dispute</strong>) between a User and the FPX (together, the <strong>Disputing Parties</strong> and each a <strong>Disputing Party</strong>):</p>
<p>1 The Disputing Parties must use reasonable endeavours to resolve any and all Disputes by negotiation at first instance.</p>
<p>1. If the Disputing Parties cannot resolve their Dispute by negotiations within 30 calendar days a Disputing Party may, by written notice to the other, require that the Dispute be dealt with by mediation under the following terms:</p>
<p>1) The mediation shall be conducted in accordance with the Mediation Protocol of the Arbitrators' and Mediators' Institute of New Zealand Incorporated (AMINZ) then in force (or any protocol or mediation agreement which replaces it).</p>
<p>2) The mediation shall be conducted by a mediator and at a fee agreed in writing by the Disputing Parties. Failing agreement between the Disputing Parties within 14 calendar days of the giving of the notice requiring mediation, the mediator will be selected and his or her fee determined by the chairperson for the time being of AMINZ (or his or her nominee).</p>
<p>3) The mediation shall take place in Auckland, New Zealand at such address as determined by the mediator[, provided that any Disputing Party may, if permitted by the mediator, attend via telephone conference, video conference or any similar means of electronic, audio or audio-visual communication].</p>
<p>4) The costs of the mediation, excluding the Disputing Parties' own legal and preparation costs, will be shared equally by the Disputing Parties.</p>
<p>2 No Disputing Party may initiate or commence court or arbitration proceedings relating to a Dispute unless it has complied with the procedure set out in this clause 18, provided that application may still be made to the courts:</p>
<p>1. for interlocutory relief; or</p>
<p>2. to recover a debt payable.</p>
<h2 id="legal-26"><span>26.</span> Amendments</h2>
<p>26.1 FPX reserves the right to amend these Terms at any time with or without notice to Users. Any User who continues to use the Website and/or the Platform after any amendments will be deemed to have agreed to such amendments.</p>
<h2 id="legal-27"><span>27.</span> Changes to the Website and Platform</h2>
<p>27.1 FPX is permitted (in its sole and absolute discretion) to alter the Website and/or the Platform, including all content, format, features and functionality, with or without notice to Users and shall incur no liability for doing so.</p>
<h2 id="legal-28"><span>28.</span> Branding</h2>
<p>28.1 No User may publish or use FPX's trade marks, brand, branding or logos except with FPX's prior written consent and directions as to such publication and use (which may be given or withheld at its sole and absolute discretion).</p>
<h2 id="legal-29"><span>29.</span> Termination or suspension of accounts</h2>
<p>29.1 If a User does not comply with these Terms FPX may terminate or suspend that User's account or membership with FPX and refuse to provide its products and/or services to that User (including access to the Platform) for any reason and at any time.</p>
<h2 id="legal-30"><span>30.</span> Breakdown and malfunctions</h2>
<p>30.1 FPX will not be liable for any loss or damage suffered as a result of any partial or total breakdown of the Website and/or the Platform or any technical malfunctions on it, the Website and/or the Platform being unavailable or performing slowly, or any viruses or other forms of interference that may damage any User's computer system.</p>`;
