export const privacyPolicy = {
  title: "Privacy Policy",
  lastUpdated: "21 September 2026",
  toc: [["1","About this policy"],["2","What information we collect"],["3","How we collect information"],["4","How we use personal information"],["5","Website enquiries and subscriptions"],["6","Cookies and similar technologies"],["7","Service providers and disclosure"],["8","Overseas processing"],["9","Storage, security and retention"],["10","Your privacy rights"],["11","Marketing communications"],["12","Privacy breaches"],["13","Changes to this policy"],["14","Contact us"]] as [string,string][],
  html: `<h2 id="legal-1"><span>1.</span> About this policy</h2>
<p>Forest Products Exchange Limited (company number 8469278) (<strong>FPX</strong>, <strong>we</strong>, <strong>us</strong> or <strong>our</strong>) is committed to handling personal information in accordance with the New Zealand Privacy Act 2020 and the Information Privacy Principles.</p>
<p>This Privacy Policy explains what personal information we may collect through the FPX website, FPX Sourcing, enquiries, subscriptions and our business relationships, why we collect it, how we may use or disclose it, and how you can request access to or correction of your information.</p>
<p>Where another privacy law applies to a particular individual or activity, including the GDPR where applicable, we will also meet the requirements that apply to us under that law.</p>
<h2 id="legal-2"><span>2.</span> What information we collect</h2>
<p>Depending on how you interact with FPX, we may collect:</p><ul><li>your name, business name, role and contact details;</li><li>information you provide in a timber sourcing request, enquiry, account registration, order or other communication;</li><li>subscription preferences and records of consent for marketing communications;</li><li>account, transaction and service information relevant to FPX Sourcing;</li><li>technical information generated when you use our website or platform, such as device, browser, network, security and diagnostic information; and</li><li>information that is reasonably necessary to manage our business relationship, comply with law, protect FPX and its users, or provide our services.</li></ul>
<p>We do not intentionally request sensitive personal information through our public website unless it is reasonably necessary for a specific purpose.</p>
<h2 id="legal-3"><span>3.</span> How we collect information</h2>
<p>We generally collect personal information directly from you when you contact FPX, use a form, subscribe to Saw Point, register for or use FPX Sourcing, place or manage an order, or otherwise communicate with us.</p>
<p>We may also receive information from your organisation, a person authorised to act for you, a service provider involved in a transaction, or a publicly available business source where collection is lawful and reasonably necessary for our activities.</p>
<h2 id="legal-4"><span>4.</span> How we use personal information</h2>
<p>We may use personal information to:</p><ul><li>provide, operate, support and improve the FPX website and FPX Sourcing;</li><li>respond to enquiries and timber sourcing requirements;</li><li>manage accounts, orders, deliveries and business relationships;</li><li>communicate service, operational and account information;</li><li>send marketing or industry communications where we have an appropriate basis to do so;</li><li>protect the security, integrity and availability of our systems and services;</li><li>prevent misuse, investigate incidents and enforce our legal rights;</li><li>comply with legal, regulatory, accounting and tax obligations; and</li><li>create aggregated or de-identified information for business analysis and service improvement.</li></ul>
<p>If we collect information for a particular stated purpose, we will not use it for an unrelated purpose unless that use is permitted by law.</p>
<h2 id="legal-5"><span>5.</span> Website enquiries and subscriptions</h2>
<p>When you use the Contact FPX form, we collect the details you submit, such as your name, company, email address, phone number, enquiry type and message. The form is delivered to the FPX team using an email delivery service.</p>
<p>When you subscribe to Saw Point, we collect your name and email address and pass those details to the systems used by FPX to manage the subscription and send the publication.</p>
<p>You do not have to provide information requested by a public website form, but if you do not provide the information marked as required we may be unable to respond to the enquiry or complete the requested service.</p>
<h2 id="legal-6"><span>6.</span> Cookies and similar technologies</h2>
<p>Our website may use browser storage, cookies and similar technologies for functions such as security, remembering preferences and recording privacy choices. FPX also uses Google Analytics 4 for optional website analytics when a visitor chooses to enable Analytics through our consent controls.</p>
<p>When Analytics is enabled, Google Analytics may process website usage and technical information to help FPX understand visits, page use and website performance. Analytics is disabled unless you choose to enable it and can be changed at any time through <a href="/cookie-settings">Cookie Settings</a>. FPX does not intentionally load non-essential advertising trackers through its public website code. See our <a href="/cookie-policy">Cookie Policy</a> for more information.</p>
<h2 id="legal-7"><span>7.</span> Service providers and disclosure</h2>
<p>We may disclose or make information available to trusted service providers where reasonably necessary to operate FPX, including providers that host or secure our systems, deliver email, support forms and subscriptions, provide website analytics such as Google Analytics where enabled, provide business software, or assist with professional services.</p>
<p>We may also disclose information where you authorise us to do so, where disclosure is connected with the purpose for which the information was collected, where required or permitted by law, or where reasonably necessary to protect FPX, our users or another person.</p>
<p>Service providers are expected to handle personal information only for the services they provide to us and subject to appropriate safeguards.</p>
<h2 id="legal-8"><span>8.</span> Overseas processing</h2>
<p>Some technology and service providers used by FPX may process or store information outside New Zealand. Where New Zealand Privacy Act requirements apply to an overseas disclosure, FPX will take reasonable steps to ensure the disclosure is permitted and that appropriate privacy safeguards are in place.</p>
<h2 id="legal-9"><span>9.</span> Storage, security and retention</h2>
<p>We take reasonable technical and organisational measures to protect personal information against loss, misuse, unauthorised access, modification and disclosure.</p>
<p>No internet service can guarantee absolute security. You are responsible for keeping account credentials and one-time access codes confidential and for notifying FPX if you believe your account or information has been compromised.</p>
<p>We retain personal information only for as long as reasonably necessary for the purpose for which it was collected, to manage our relationship with you, and to satisfy legal, accounting, dispute-resolution and other legitimate business requirements. Information that is no longer required will be deleted, anonymised or otherwise securely disposed of where reasonably practicable.</p>
<h2 id="legal-10"><span>10.</span> Your privacy rights</h2>
<p>Under the Privacy Act 2020, you may request confirmation of whether FPX holds personal information about you, ask to access that information, and ask us to correct information you believe is wrong.</p>
<p>We may need to verify your identity before completing a privacy request. In some circumstances the law permits or requires us to withhold information. If that applies, we will explain the basis for our decision where we are permitted to do so.</p>
<p>Depending on the law applicable to you, you may have additional privacy rights. Contact us if you wish to exercise a privacy right and we will assess the request under the law that applies.</p>
<h2 id="legal-11"><span>11.</span> Marketing communications</h2>
<p>FPX may send commercial electronic messages where we have consent or another lawful basis to do so. Marketing emails will identify the sender and include a functional way to unsubscribe.</p>
<p>You can withdraw from marketing communications at any time using the unsubscribe option in the message or by contacting <a href="mailto:support@fpx.nz">support@fpx.nz</a>. Operational or service messages that are necessary to manage an account, transaction or request may still be sent where appropriate.</p>
<h2 id="legal-12"><span>12.</span> Privacy breaches</h2>
<p>If FPX becomes aware of a privacy breach, we will assess and respond to it in accordance with the Privacy Act 2020. Where a breach is notifiable, we will notify the Office of the Privacy Commissioner and affected individuals as required by law.</p>
<h2 id="legal-13"><span>13.</span> Changes to this policy</h2>
<p>We may update this Privacy Policy to reflect changes to our services, technology, business practices or legal obligations. The current version will be published on this page with its last-updated date.</p>
<h2 id="legal-14"><span>14.</span> Contact us</h2>
<p>For privacy questions, access or correction requests, or concerns about how FPX has handled personal information, contact:</p>
<p><strong>Privacy Officer<br/>Forest Products Exchange Limited</strong><br/>Email: <a href="mailto:support@fpx.nz">support@fpx.nz</a><br/>Website: <a href="https://www.fpx.nz/contact-us">www.fpx.nz/contact-us</a></p>
<p>You can also find information about your privacy rights and make a complaint to the Office of the Privacy Commissioner at <a href="https://www.privacy.org.nz" target="_blank" rel="noreferrer">privacy.org.nz</a>.</p>`,
};