"use client";
import { Eyebrow, Arrow, AppButtons, SourcePageCTA, InnerHero, PageCTA, Breadcrumbs } from "./master-shared";

function SourceRouteCards(){const routes=[
  {num:"01",eyebrow:"YOU KNOW WHAT YOU NEED",title:"Create a request",copy:"Send the product, specification and quantity you need. FPX will review the requirement and source suitable options.",cta:"Create a request",href:"https://app.fpx.nz/request-cart"},
  {num:"02",eyebrow:"SEE WHAT IS AVAILABLE",title:"Browse timber",copy:"Explore available stock and product information when you are ready to buy from current listings.",cta:"Browse timber",href:"https://app.fpx.nz/shop"},
  {num:"03",eyebrow:"CURRENT OPPORTUNITIES",title:"View offers",copy:"Review current timber opportunities and enquire when an offer fits your requirement.",cta:"View offers",href:"https://app.fpx.nz/offers"}
];return <section className="m-source-routes m-animate-in"><div className="m-source-routes-head"><Eyebrow>THREE WAYS TO START</Eyebrow><h2>Start with what<br/><em>you already know.</em></h2><p>You do not need to learn a process before using FPX. Choose the entry point that best matches your requirement.</p></div><div className="m-source-routes-grid">{routes.map(route=><a key={route.num} href={route.href}><span>{route.num}</span><small>{route.eyebrow}</small><h3>{route.title}</h3><p>{route.copy}</p><b>{route.cta}<Arrow/></b></a>)}</div></section>}

function SourceProcess(){const steps=[["01","Share the detail","Add the dimensions, grade, treatment, quantity and timing that matter to the job."],["02","Review the options","FPX keeps product information and sourcing options clear so your team can compare what fits."],["03","Confirm the order","Choose the option that works for your requirement and move into the order process."],["04","Keep it connected","Use your FPX account to follow orders, deliveries and previously ordered products."]];return <section className="m-source-process m-animate-in"><div><Eyebrow>WHAT HAPPENS NEXT</Eyebrow><h2>From requirement<br/><em>to delivery.</em></h2></div><div className="m-source-process-list">{steps.map(([num,title,copy])=><article key={num}><span>{num}</span><div><h3>{title}</h3><p>{copy}</p></div></article>)}</div></section>}

function SourceAccountStrip(){return <section className="m-source-account-strip m-animate-in"><div><Eyebrow>YOUR FPX ACCOUNT</Eyebrow><h2>Orders, deliveries and repeat requirements in one place.</h2></div><div><span>MY ORDERS</span><span>MY DELIVERIES</span><span>PREVIOUSLY ORDERED</span></div></section>}

export function SourceTimberPage(){return <><Breadcrumbs items={[["Home","/"],["FPX Sourcing","/source-timber"]]}/><section className="m-source-hero m-source-hero-revamp"><div className="m-source-hero-copy"><Eyebrow>SOURCE TIMBER THROUGH FPX</Eyebrow><h1>A better way<br/><em>to source timber.</em></h1><p>Browse available timber, review current offers or send FPX a specific requirement. Start with the route that fits the job.</p><AppButtons/></div><div className="m-source-hero-visual" data-master-parallax data-speed=".12"><img src="/images/product-groups/manufacturing/manufacturing-warehouse-bundles.png" alt="Commercial timber bundles in New Zealand"/></div></section><SourceRouteCards/><SourceProcess/><SourceAccountStrip/><SourcePageCTA/></>}

export function HowPage(){const steps=[["Start where you are","Shop available stock, review current offers or send a specific request. Start with the route that best matches what you know."],["Share the detail","Add the dimensions, grade, treatment and quantity that matter to the job. Clear inputs make the next step easier."],["Choose what fits","Review the timber options and the information around them, then choose the route that works for your team."],["Keep it moving","FPX keeps the order and delivery path connected so your team can follow the handover through to site."]];return <><Breadcrumbs items={[["Home","/"],["How FPX Works","/how-fpx-works"]]}/><InnerHero slug="how-fpx-works"/><section className="m-how-page-flow m-animate-in"><div className="m-how-page-intro"><Eyebrow>WHAT HAPPENS NEXT</Eyebrow><h2>From requirement<br/><em>to delivery.</em></h2><p>Once you start, FPX keeps the practical details moving, from the first specification through to the final handover.</p></div><div className="m-how-page-cards">{steps.map((s,i)=><article key={s[0]}><div className="m-how-page-marker" aria-hidden="true"/><div><small>{["BEGIN","DETAIL","DECIDE","DELIVER"][i]}</small><h3>{s[0]}</h3><p>{s[1]}</p></div></article>)}</div></section><PageCTA/></>}
